- action:
  - data:
      message: Home Assistant {{ states.updater.updater.state }} is now available
    service: notify.ios_allan_kleins_iphone
  alias: Update Notification
  condition: []
  id: '1508223476962'
  trigger:
  - entity_id: updater.updater
    platform: state
- action:
  - data:
      message: SSL certificate expires in {{ states.sensor.ssl_certificate_expiry.state
        }} days
    service: notify.ios_allan_kleins_iphone
  alias: SSL Certificate Expiry
  condition:
  - below: '10'
    condition: numeric_state
    entity_id: sensor.ssl_certificate_expiry
  id: '1508223580828'
  trigger:
  - at: 09:00
    platform: time
