- platform: ring
  monitored_conditions:
    - ding
    - motion

- platform: hikvision
  host: !secret nvr_host
  port: 80
  ssl: false
  username: !secret hikvision_user
  password: !secret hikvision_password
  motion_2:
    delay: 30
  motion_3:
    delay: 30
  motion_4:
    delay: 30
  motion_5:
    delay: 30
  motion_7:
    delay: 30
