- alias: Driveway motion
  id: driveway_motion
  trigger:
  - entity_id: binary_sensor.nvr_line_crossing_3
    platform: state
    to: 'on'
  - entity_id: binary_sensor.master_closet_motion_sensor
    platform: state
    to: 'on'
  action:
    service: notify.ios_allaniphone
    data:
      message: Driveway Motion Detected
      data:
        push:
          category: garage_event
          sound: US-EN-Alexa-Motion-In-Front-Yard.wav
        entity_id: camera.driveway
        attachment:
          url: "{{ state.sensor.camera_driveway_url.state }}"
          content-type: jpg


- alias: Backyard motion
  id: backyard_motion
  trigger:
  - entity_id: binary_sensor.nvr_line_crossing_5
    platform: state
    to: 'on'
  action:
    - service: notify.ios_allaniphone
      data:
        message: Back Yard Motion Detected
        data:
          push:
            category: concerning_event
            sound: US-EN-Alexa-Motion-In-Back-Yard.wav
          entity_id: camera.backyard
          attachment:
            url: "{{ state.sensor.camera_backyard_url.state }}"
            content-type: jpg

- alias: West Gate motion
  id: west_gate_motion
  trigger:
  - entity_id: binary_sensor.nvr_line_crossing_4
    platform: state
    to: 'on'
  action:
    - service: notify.ios_allaniphone
      data:
        message: West Gate Motion Detected
        data:
          push:
            category: concerning_event
            sound: US-EN-Alexa-Motion-In-Back-Yard.wav
          entity_id: camera.west_gate
          attachment:
            url: "{{ state.sensor.camera_west_gate_url.state }}"
            content-type: jpg
