homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml
#  customize_glob: !include custom-ui.yaml
  packages: !include_dir_named packages

# Custom UI from https://github.com/andrey-git/home-assistant-custom-ui
#customizer:
#  custom_ui: local

# Enables the frontend
frontend:
  themes:
    darkblue:
      primary-color: "#396FB6"
      light-primary-color: "#77a0d4"
      dark-primary-color: "#3539ce"
      text-primary-color: "#ffffff"
      primary-background-color: "#37464f"
      sidebar-text_-_background: "#3c4348"
      paper-card-background-color: "#263137"
      paper-card-header-color: "var(--text-primary-color)"
      secondary-background-color: "var(--primary-background-color)"
      primary-text-color: "var(--text-primary-color)"
      secondary-text-color: "var(--primary-color)"
      paper-listbox-background-color: "var(--sidebar-text_-_background)"
      paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-button-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-bar-color: "var(--dark-primary-color)"
      paper-slider-knob-color: "var(--primary-color)"
      paper-slider-knob-start-color: "var(--primary-color)"
      paper-slider-pin-color: "var(--primary-color)"
      paper-slider-active-color: "var(--primary-color)"
      paper-slider-secondary-color: "var(--light-primary-color)"
      paper-slider-container-color: "var(--sidebar-text_-_background)"
      paper-progress-secondary-color: "var(--sidebar-text_-_background)"
      paper-item-selected_-_background-color: "var(--primary-color)"
      paper-item-icon_-_color: "var(--text-primary-color)"
      paper-item-icon-color: "var(--text-primary-color)"
      paper-item-icon-active-color: "var(--primary-color)"
      paper-grey-50: "var(--sidebar-text_-_background)"
      paper-grey-200: "var(--primary-background-color)"
      label-badge-background-color: "var(--sidebar-text_-_background)"
      label-badge-text-color: "var(--text-primary-color)"
      label-badge-red: "var(--primary-color)"
      label-badge-blue: "var(--light-primary-color)"
      label-badge-green: "var(--dark-primary-color)"
      label-badge-yellow: "var(--text-primary-color)"
      label-badge-grey: "var(--paper-grey-500)"
      table-row-background-color: "var(--paper-card-background-color)"
      table-row-alternative-background-color: "var(--sidebar-text_-_background)"

# Enables configuration UI
config:

http:
  api_password: !secret api_password
  base_url: !secret base_url
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem
  server_port: 8123
  use_x_forwarded_for: true
#  trusted_networks:
#    - 192.168.1.0/24
#    - 192.168.2.0/24
  ip_ban_enabled: True
  login_attempts_threshold: 3

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: home-assistant-1
  discovery: true
  discovery_prefix: smartthings
  keepalive: 60

updater:
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  include:
    domains:
      - alarm_control_panel
      - lock
      - binary_sensor
      - device_tracker
      - switch
      - vacuum
  exclude:
    domains:
      - light

# View all events in a logbook
logbook:

# Track the sun
sun:

# Enable iOS
ios: !include ios.yaml

# Text to speech
tts:
  - platform: google
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_id
    aws_secret_access_key: !secret aws_secret_access_key
group: !include_dir_merge_named groups

#automation: !include automations.yaml
automation old: !include_dir_merge_list automations
script: !include_dir_merge_named scripts
python_script:

# Physical Devices
light: !include light.yaml
switch: !include switches.yaml
sensor: !include_dir_merge_list sensors
# none for now, replaced with packages
binary_sensor: !include binary_sensors.yaml
# none for now, replaced with packages
#camera: !include cameras.yaml
ffmpeg:
# replaced with climate.yaml
#ecobee: !include ecobee.yaml
device_tracker: !include device_trackers.yaml
media_player: !include media_players.yaml

# Virtual Devices
google_assistant: !include google_assistant.yaml
ifttt: !include ifttt.yaml
notify: !include notify.yaml
twilio: !include twilio.yaml
logger: !include logger.yaml
google: !include google.yaml
#remote: !include remote.yaml
#usps: !include usps.yaml
#alexa: !include alexa.yaml
shell_command: !include shell_commands.yaml
scene: !include_dir_list scene
#image_processing: !include image_processing.yaml
#logentries: !include logentries.yaml
#bloomsky: !include bloomsky.yaml
#tesla: !include tesla.yaml
zone: !include zone.yaml
variable: !include variable.yaml

# Inputs
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
input_number: !include input_number.yaml

# Enable emulated Hue for Alexa - disabled in favor of haaska
#emulated_hue:
#  expose_by_default:
#    - switch
#    - light
#    - media_player

# Enable Z-Wave stick
zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
  device_config:
    cover.rear_lower_shade_level:
      invert_openclose_buttons: true
    cover.rear_upper_shade_level:
      invert_openclose_buttons: true
    cover.rear_shades_level:
      invert_openclose_buttons: true

# Enable Zigbee stick
#zha:
#  usb_path: /dev/ttyACM1
#  database_path: /config/zigbee.db

# Menu Customization
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret configurator_url
  ide:
    title: IDE
    icon: mdi:file-document
    url: !secret editor_url
  terminal:
    title: Terminal
    icon: mdi:console-line
    url: !secret terminal_url
  mdiindex:
    title: MD Icon Index
    icon: mdi:vector-square
    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html

