- platform: mqtt
  name: "Garage Door"
  state_topic: "smartthings/Garage Door/contact/state"
  command_topic: "smartthings/Garage Door/door/cmd"
  state_open: "open"
  state_close: "closed"
  payload_open: "open"
  payload_close: "closed"
  retain: true
  optimistic: true
