# Connect to Ubiquiti access point for wifi device state
- platform: unifi
  host: !secret unifi_ap
  username: !secret unifi_username
  password: !secret unifi_password
  verify_ssl: false
  ssid_filter:
    - 'Thunder'
    - 'Home-IoT'
    - 'Home-IoT5'

#- platform: icloud
#  username: !secret icloud_username
#  password: !secret icloud_password
#  track_new_devices: yes
#  interval_seconds: 1800
#  consider_home: 180

- platform: owntracks_http

#- platform: ping
#  hosts:
#    allan_ping: iphone.home.local
