- platform: mqtt
  name: "Front Door Lock"
  state_topic: "smartthings/Front Door/lock/state"
  command_topic: "smartthings/Front Door/lock/cmd"
  payload_lock: "locked"
  payload_unlock: "unlocked"
  optimistic: false
  retain: true

- platform: mqtt
  name: "Back Door Lock"
  state_topic: "smartthings/Back Door/lock/state"
  command_topic: "smartthings/Back Door/lock/cmd"
  payload_lock: "locked"
  payload_unlock: "unlocked"
  optimistic: false
  retain: true

- platform: mqtt
  name: "Back Gate Lock"
  state_topic: "smartthings/Back Gate/lock/state"
  command_topic: "smartthings/Back Gate/lock/cmd"
  payload_lock: "locked"
  payload_unlock: "unlocked"
  optimistic: false
  retain: true
