- platform: mqtt
  name: "Fireplace"
  state_topic: "smartthings/Fireplace/switch/state"
  command_topic: "smartthings/Fireplace/switch/cmd"
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  retain: true

- platform: mqtt
  name: "Theater Switch"
  state_topic: "smartthings/Theater Switch/switch/state"
  command_topic: "smartthings/Theater Switch/switch/cmd"
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  retain: true

- platform: mqtt
  name: "Towel Rack"
  state_topic: "smartthings/Towel Rack/switch/state"
  command_topic: "smartthings/Towel Rack/switch/cmd"
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  retain: true

- platform: mqtt
  name: "Guest Bedroom Fan"
  state_topic: "smartthings/Guest Bedroom Fan/switch/state"
  command_topic: "smartthings/Guest Bedroom Fan/switch/cmd"
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  retain: true

- platform: mqtt
  name: "Rear Bedroom Fan"
  state_topic: "smartthings/Rear Bedroom Fan/switch/state"
  command_topic: "smartthings/Rear Bedroom Fan/switch/cmd"
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  retain: true

#- platform: command_line
#  switches:
#   receiver:
#    oncmd: "/usr/local/bin/onkyo PWR01"
#    offcmd: "/usr/local/bin/onkyo PWR00"
#    cableinput: "/usr/local/bin/onkyo SLI01"
#    shieldinput: "/usr/local/bin/onkyo SLI02"
#    piinput: "/usr/local/bin/onkyo SLI05"

- platform: mqtt
  name: "Cable"
  state_topic:   "harmony-api/activities/watch-tv"
  command_topic: "harmony-api/activities/watch-tv/command"
  payload_on: "on"
  payload_off: "off"

- platform: mqtt
  name: "Shield"
  state_topic:   "harmony-api/activities/watch-shield"
  command_topic: "harmony-api/activities/watch-shield/command"
  payload_on: "on"
  payload_off: "off"

- platform: mqtt
  name: "Stream Music"
  state_topic:   "harmony-api/activities/listen-to-music"
  command_topic: "harmony-api/activities/listen-to-music/command"
  payload_on: "on"
  payload_off: "off"

- platform: mqtt
  name: "Alarm Toggle"
  state_topic: "smartthings/Alarm/switch/state"
  command_topic: "smartthings/Alarm/switch/cmd"
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  retain: true

- platform: rachio
  access_token: !secret rachio_api_key

- platform: hikvisioncam
  host: 192.168.254.2
  name: Front Door Camera Motion
  username: !secret hikvision_user
  password: !secret hikvision_password

- platform: hikvisioncam
  host: 192.168.254.3
  name: Downstairs Camera Motion
  username: !secret hikvision_user
  password: !secret hikvision_password

- platform: hikvisioncam
  host: 192.168.254.11
  name: Backyard Camera Motion
  username: !secret hikvision_user
  password: !secret hikvision_password

- platform: hikvisioncam
  host: 192.168.254.13
  name: West Gate Camera Motion
  username: !secret hikvision_user
  password: !secret hikvision_password

- platform: hikvisioncam
  host: 192.168.254.12
  name: Driveway Camera Motion
  username: !secret hikvision_user
  password: !secret hikvision_password

- platform: broadlink
  host: 192.168.3.92
  mac: '34:ea:34:90:f8:29'
  switches:
    master_left_window:
      friendly_name: "Master Left Window"
      command_on: 'sgAKAaUUFQcLExUHCxILEgsSFQgVCAoTChMVCBUIChIVCAsSCxILEhUIChMVCAoTChMVBwsSFQgLEgoTFQgVCAoTChMKEwoSCxMKEgsSCxIKEwoTFQgKEwoTChMKEgsSCxILEgsSCxILEgoTChMVCAoTFQgVBwsSCxIVCAsSFQgKExUIChIVo6UUFQcLEhUICxILEgoTFQgVCAoTChMVCBUIChIWBwsSCxILEhUIChMVBwsSCxIVCAsSFQgKEwoTFQgVCAoTChILEgsSCxILEgsSChMKEwoTFQgKEgsSCxILEgsSCxILEgoTChMKEwoSCxIVCAsSFQgVCAoTChMVCAoTFQgKExUHCxIUAAXcAAAAAAAAAAAAAAAAAAA='
      command_off: 'sgCyAgsSChMKExUIFAkKEhUIFQgKEwoTChMVCAoSFaKmExUIChMVCAoTChILEhUIFQgKEwoTFQgVCAoTFQcLEgsSCxIVCAoTFQgKEgsSFQgLEhUIChMKExUIFQgKEgsSCxILEgsSCxIKEwoTChILEhYHCxILEgoTChMKEwoTChILEgsTFAgLEgsSChMKExUIFQgKExQIFQgLEgsSChMVCAoSFaOlExUIChMVCAoTChMKEhUIFQgLEgsSFQgVCAoTFQcLEgsSCxIVCAoTFQgKEwoTFQgKExUHCxILEhUIFQgLEgoTChILEgsSCxILEgsSChMLEhUIChMKEgsSCxILEgsSChMKEwoTFQgKEgsSCxILEhUIFQgKExUIFQgKEgsSCxIVCAsSFKOmExUIChMVBwsSCxILExQIFQgLEgoTFQgVBwsTFQcLEgsSCxIVCAoTFQgKEwoTFQcLEhYHCxILEhUIFQgKEwoTChMKEgsTChILEgsSCxILEhUIChMKEwoTChMKEgsSCxILEgsSFQgLEgoTChMKExUIFQcLEhYHFQgKEwoTChMVBwsSFaOlExYHCxIWBwsSCxIKExUIFQgKEwoTFQgUCAsSFgcKEwsSCxIVCAoTFQgKEgsSFgcLEhUIChMLEhUIFQcLEgsSCxILEgsSChMLEgsSChMKExUHCxILEgsSCxIKEwoTChMKEwoTFQgKEgsSCxILEhUIFQgKExUIFQcLEgsSCxIWBwsRFaOmExUIChMVCAoSCxILEhUIFQgKEwoTFQgVBwsSFgcLEgsSCxIVCAoTFQcLEgsTFQcLEhUICxILEhUIFQgKEgsSCxILEgsSCxIKEwoTChMKExUIChILEgsSCxILEgsSChMKEwoTFQgKEgsSCxILEhUIFQgKExUIFQcLEgsSCxIVCAoSFQAF3BUIFQcLEg=='
    master_balcony_left_window:
      friendly_name: "Balcony Left Window"
      command_on: 'sgGEAwoTChMUCQoTFAgLEgsSFQgVCAoTChMKEwoTChMKEwoTChIKFBQICxIKEwoTChMKEwoTChMKEwoSCxMKEgsSChMVCAoTFQgVCAoTChMVCAoTFQgKExQIFQgUowoTCxIKEwoTChMKEwoTChOlFBUIChMUCQoSCxILEhUIFQgKEwoTFQgVCAoTFQgKEwoSCxMUCAoTFQgKEwoTFQgKExUIChMKExUIFAkKEgoTChMKEwoTChMKEwoTChMVCAoTChMKEwoTChIKEwoTChMKEwoTChMVCAoTChMUCQoSCxILEhUIChMKEwoTFQgKEwoSFaOlFBQJChMUCAsSCxIKExUIFQgKEwoTFAkUCQoTFAkJEwoTCxIVCAoTFQgKEwoTFAkKExQICxIKExUIFQgKEwoTChMKEwoTChMKEgsSChQUCAoTChMKEwoTChMKEwoTChILEgoTChMVCAoTChMVCAoTChMKExQJChMKEgsSFQgKEwoSFaOlFBUIChMUCQoSCxMJFBQIFQgKEwoTFQgVBwsTFAgLEgsSChMVCAoTFQgKEwoTFAkKExQIChMKExUIFQgKEwoTChMKEwoTChIKEwoTChMVCAoTChMKEwoSCxILEgsSChMKEwoTChMVCAoTChMUCQoTChILEhUIChMKEwoTFQgKEwoSFKSlFBQICxMUCAoTChMKExUIFQgKEgsTFAgVCAsSFQgKEwoTChMVCAoTFAgLEgsTFAgKExUIChMKExUIFQgKEwoTChIKEwsSCxIKEwoTChMVCAoTChMKEgsSCxMJEwoTChMKEwoTChMVCAoTChMUCAsSCxIKExUIChMKEwoTFAkKEgsSFKSlExUIChMVCAoTChMKExUIFAkKEwoTFAkUCAoTFQgKEwoTChMVCAoTFAkKEgsTFAgKExUIChMKExUIFQgKEwoSCxILEgsSChMKEwoTChMVCAoTChMKEwoSCxMJEwoTChMKEwoTChMVCAoTChMUCAsTCRMKExUIChMKEwoTFQcLEwoSFKSlFBQICxMUCAoTChMKExUIFQgKEwoTFAgVCAsSFQgKEwoTChMVCAoTFQgKEwoTFQgKExQIChMKExUIFQgKEwoTChMKEwoTChILEgsSChQUCAoTChMKEwoTChMKEgsSCxIKEwoTChMVCAoTChMVCAoTChMKExQICxIKEwoTFQgKEwoSFQAF3AAAAAA='
      command_off: 'sgDOAggUFAkJFAkUCRQJFAkUCRQJEwkUCRQJFAkUFAkJFAkUFAkJFAkUCRQTCQoTChMJFBQJCRQJExSkpBUUCQkUEwoJFAkTCRUTCRQJCRQJFBQJFAkJFBQJCRQJEwoTFAkKExQJCRQJFBQJCRQTCgkUCRQTCRQJCRQJFAkUCRQJFAkUCRQJEwoTFAkJFAkUCRQJFAkUCRQJFAkUCRMKEwoTFAkJFAkUFAkJFAkUCRQTCgkUCRMKExQJCRQJExSkpBUUCQkUEwoJFAkTChMUCRQJCRQJFBQJFAkJFBQJCRMKFAkTFAkKExQJCRQJFBMKCRQUCAoUCRQTChMJChMJFAkUCRQJFAkUCRQJFAkUEwkKEwoTCRQJFAkUCRQJFAkUCRMKEwoTFAkJFAkUFAkJFAkUCRQUCQkUCRMKFBMJChMJFBOkpBUUCQkUFAkJFAkUCRQTCRQJChMJFBQJFAkJFBMKCRMKEwoTFAkKExQJCRQJFBQJCRQUCQkTChMUCRQJChMJFAkUCRQJFAkUCRMKEwoTFAkJFAkUCRQJFAkUCRQJFAkUCRMKFAkTFAkKEwkUFAkJFAkUCRQTCgkUCRMKExQJCRQJExSkpBUUCQkUEwoJEwoTChMUCRQJCRQJFBQJFAkJFBQJCRMKEwoTFAkKExQJCRQJFBQJCRQTCQoTChQTCRQJChMJFAkUCRQJFAkUCRQJEwoUEwkJFAkUCRQJFAkUCRQJFAkTChMJFAkVEwkKEwkUFAkJFAkUCRQTCQoUCRMKFBMJCRQJExSkpBUUCQkUEwoJFAkUCRQTCRQJCRQJFRMJFAkJFBQJCRQJEwkVEwkKExQJCRQJFBQJCRQTCgkUCRQTChMKCBQJFQgUCRQJFAkUCRQJFAkUEwoJFAgVCRMJFAkUCRQJFAkUCRQJFAkUEwkJFQgUFAkJFAkUCRQTCgkUCRQJExQKCBQJExQABdwJFAkUCRQJFAkU='
    master_balcony_right_window:
      friendly_name: "Balcony Right Window"
      command_on: 'sgGEAwgVEwoIFBQJCRQJFBQJFAkJFAkTChMJFAkUCRQJFAkUFAkJFAkUCRQJEwoTCRQKEwkUCRQJFAkUCRQJFAgVEwoJExQJFAkJFAkUFAkJFBMKEwoJFBMJEwABYwkUCRQJFAkUCRQIFQkUCRSkFRMJCRQUCQkUCRQJFBMKEwoJFAgVEwoTCQkVEwkJFAkUCRQTCgkUEwoJEwoTFAkJFRMJCRQJFBMKEwoJFAkTChMJFQgUCRQJFAkUFAkJFAkUCBUJFAkTCRUIFAkUCRQJFAkUCRQTCgkUCRQTCQkVCBQJFBQJCRQJFAkUFAkUCQkTE6WkFRMJCRUTCQkUCRQJFBQJEwoJFAkUEwoTCggVEwkJFAkUCRQUCQkUEwoJFAkUEwoIFRMJCRQJFBQJFAkJFAkUCRQJEwoUCBUIFAkUFAkJFAkUCRQJFAkUCRQJFAgVCBQJFAkUCRQUCQkUCRQTCgkTChQIFBQJCRQJFAkUEwoUCQkTE6WkFRMKCBUTCQkUCRQJFBQJFAkJFAkUEwoTCQoUEwkJFAkUCRQUCQkUEwoJFAkUEwkJFBQJCRQJFBQJFAkJFAkUCBUJFAgUCRUIFAkUFAkJFAkUCRQJFAkUCRMKFAkTChQIFAkUCRQTCgkUCRQTCgkUCRQJFBMJChMJFQgUFAkTCgkTFKSkFRQJCRQTCgkUCRQJFBMJFAkJFAkUFAkUCQkUFAkJFAkTCRUTCQkUFAkJFAkUEwoJFBQJCRQJFBMKEwoJEwoTCRQJFAkUCRQJFAkUEwoJFAkUCRMJFAkUCRQJFAkUCRQJFAkUCRQTCggUCRUTCQkUCRQJFBQJCRQJFAkUEwoTCgkTE6WkFRMJCRQUCQkUCRQJFBQJEwoJFAkUEwoTCQkUFAkJFAkUCRQTCgkUEwoJFAkUEwoIFBQJCRQJFBQJEwoJFAkUCRQJFAgVCBUIFAkUFQgKEgsSCxIKEwsSChQJFAkUCRQIFAkUChMUCQkUCRQUCQkTChQJFBMKCRMKEwkVEwkUCQkUE6SkFRQJCRQTCgkUCRQJFBMJFAkJFAkUFAkUCQkUFAkJFAkUCRQTCQoUEwkJFAkUFAkJFBQJCRQJFBMKEwoIFQgUCRQJFAkUCRQJFAkUEwoJFAkUCRQJFAkTCRQJFAkUCRQJFAkUCRQUCQkUCRQTCgkUCBQJFRMJCRQJFAkUFAkUCQkTFAAF3AAAAAA='
      command_off: 'sgAOAgkUFAkJFAkUCRQUCBQJChMKExQJFAkJFBQJCRQJFAkTFAkKExQJCRQJFBQJCRQUCQkTChMUCRQJChMJFAkUCRQJFAkUCRMKExQJChMKEwkUCRQJFAkUCRMKEwoTChMKEwoTFAkJFAkUFAkJEwoUCRMUCQoTChMKExQJFAkJExSkpBQVCAoTFAkKEwoTCRQUCRQJCRQJFBMKEwkKExQJChMJFAkUFAkJFBQIChMKExQJChMUCQkUCRQUCRQIChQJEwoTChMKEwkUCRQJFBQJCRMKFAkTChMKEwoTCRQJFAkUCRQJFAkUEwkKEwoTFAkJFAkUCRQUCAoTChMKExQJFAkKEhSkpBUUCQkUFAgKEwoTChMUCRQJChMJFBQJFAgKExUIChMKEwkUFAkKExQJCRMKFBQIChMUCQoTCRQUCRQJCRMKEwoTChMKEwoTChMJFBQJCRQJFAkUCRMKEwoTChMKEwoTCRQJFAkUFAkJEwoTFQgKEwoTChMUCQkUCRQJFBQJFAgKExSjpRQUCQoTFAkJFAkUCRQUCRQJCRMKExQJFAkKExQJCRQJEwoTFQgKExQJChMKExQJCRQUCQkUCRQUCBQJChMKEwoTCRQJFAoTCRQJExUIChMKEwoTChMKEwkUCRQJFAkTChMKEwoTFQgKEwoTFAkJFAkUCRQUCAoTChMKExQJFAkKEhQABdwTCQoTFAkKEwkU='
    master_right_window:
      friendly_name: "Master Right Window"
      command_on: 'sgGEAwoTFAkJExUIChMKExUIFAkKEwoTCRQJEwoTChMKFBQIChMKEwoTChMKEwkUChMJEwoTChMKEwoTChMKEwoTFAgKFBQJFAgKEwoTFAkUCQoTCRQJFBQIFAAB3woTCRQKEwkUCRMKEwoTChOlFBQJChMUCQkUCRMKFBQIFQgKEwoTFAkUCQkUFAkJFAkTChMVCAoTFQgKEwkUFAkJFBQIChMKExUIFQgKEwoTChMKEwkUChIKExUIChMKEwoTChMKEwoTCRQKEgoTChMKEwoTChMUCQoTChMUCQoTCRMKExUIChMKExUIChMUCQoSFKSlFBQJCRQUCQkTChMKExUIFQgKEwoTFAkUCAoUFAgKEwoTChMVCAoTFAkKEwoTFAkJFBQIChMKExQJFQgKEwoTCRQKEwkUCRMKExUIChMKEwoTChMJFAkUCRMKEwoTChMKEwoTChMUCQoTChMUCQoTCRMKExUIChMKExQJChMUCQoSFKSlFBQJCRQUCAoTChMKExUIFAkKEwkUFAkUCAoTFQgKEwoTChMUCQoTFAkJEwsTFAgKExUIChMKExUIFAkKEwoTCRQKEwoTCRMKExUIChMKEwoTChMKEwoTCRQKEwkTChMKEwoTChMVCAoTChMUCQoTCRMLExQIChMKExUIChMVCAoSFKSlFBQJCRQUCQoSChMKExUIFQgKEwoTFAkUCQoTFAgKEwoTChMVCAoTFQgKEwoTFAkJFBQIChMKExUIFQgKEwoTChMKEwoTChIKFBQIChMKEwoTChMKEwoTChMJFAoTCRMKEwoTChMVCAoTChMVCAoTChMKExQIChMKExUIChMVCAoSFaOlFBQJChMUCQkTCxIKExUIFQgKEwoTFAkUCQoTFAkJFAoSChMVCQkTFQgKEwoTFQgKExQJCRQKExQJFAgKEwoTChMKEwoTChMKExQICxMJEwoTChMKEwoTChMKEwoTChMKEwkUCRQUCAoTChMVCAoTChMKExQJChMKExQIChMVCAoSFaOlFBUIChMUCQkUCRQJExUIFQgKEwoTFAkVCAoTFAkKEwkUCRQUCAoTFQgKEwoTFAkKExQICxIKExUIFQgKEwoTChMKEwoTChMKExQIChMKEwoTChMKEwoTChMKEwkUChMJEwoTChMVCAoTChMUCQoTCRQJFBQIChMKExUIChMUCQoSFQAF3AAAAAA='
      command_off: 'sgGEAwkUFAgKExQJChMKExQJFAkJFAkUCRQJFAkTChMKExQJChMJFAkUCRQJFAkUCRQJEwoTCRQJFAoTFAkKEwkUCRQJFBQJFAgKExQJFAkKExQJCRQJFBQIFAABYgoUCRMKEwkUCRQKEwkUCRSkFRQJCRMVCAoTChMKExQJFAkJFAkUFAgVCAoUEwkJFAoTChMUCQkUFAkJFAkUFAgKFBMJChMKExQJFAkJFAkUCRQJFAkUCRMJFBQJCRQJFAkUCRQJFAkTChMKEwoTChMJFAkUCRQUCQkUCRQTCQoTChMKExQJCRQJFBQJCRQUCQkTFKOlFBUIChMUCQkUCRQJFBQJEwoJEwoTFAoTCQkUFAkJFAkUCRQUCQkUFAgKEwoTFAkKExQJCRQJFBQJFAgKEwoTChMKEwoTChMKExQJCRQJFAkTChMKEwoTChMJFAkUCRQJFAkUCRQUCAoTChMUCQoTChMJFBQJCRQJFBQJCRQUCAoTE6WkFBUIChMUCQoTCRQJFBQJEwoJFAkUEwkVCAoTFAkJFAkUCRQUCQkUEwkKFAkTFAkKExQJCRQJFBQJEwoJEwoTChMKEwkUCRQJFBQJCRQJFAkUCRMKEwoTCRQJFAkUCRQJEwoUCRMUCQoTChMUCQoTCRQJFBMKCRMKFBMJChMUCQoSFKSkFRQJCRQUCQkUCRMKExQJFAkKEwkUFAkUCQkUFAgKFAkTChMUCQkUFAkJFAkUFAgKExUJCRMKExQJFAkJFAkTChQJFAkUCRMKExQJChMKEwoTCRQJEwoTChMKEwoTCRQJFAkUCRQUCQkUCRMUCQoTChMJFBQJCRQJFBQJCRQUCAoTFKOlFBQJCRQUCQkUCRQJFBQJFAgKEwkUFAkUCQoTFAkJFAkTChQUCAoUEwkJFAoTFAkJFBQJCRQJFBQJFAgKEwoTChMJFAkUCRQJFBQJCRQJEwoTChMJFAoTCRQJFAoTCRQJFAkUCRQTCQoTChMUCQkUCRQJFBQJCRQJFBMKCRMUCQoSFKSkFRQJCRQUCQkUCRMKFBMJFAkJFAkUFAkUCQkUFAkJEwoTChMUCQkUFAkKEwkUFAkJFBQJCRQJExQJFAkJFAkUCRQJFAkTChMKExUIChMJFAkUCRQJFAkUCRQJEwoTCRQKEwkUCRQUCQkUCRQUCQkTChMKExQJChMJFBQJCRQUCQkTFAAF3AAAAAA='
