- platform: template
  sensors:
    harmony_theater_activity:
      friendly_name: 'Current Theater Activity'
      icon: mdi:monitor
      value_template: '{{ states.remote.theater.attributes.current_activity }}'
    harmony_bedroom_activity:
      friendly_name: 'Current Bedroom Activity'
      icon: mdi:monitor
      value_template: '{{ states.remote.master_bedroom.attributes.current_activity }}'
