security:
 view: yes
 icon: mdi:security-home
 entities:
  - group.alarmbadges
  - alarm_control_panel.home
  - lock.front_door_locked
  - lock.back_door_locked
  - lock.back_gate_locked
  - group.all_locks
  - group.tracked_users
