security:
 name: Security
 view: yes
 icon: mdi:security-home
 entities:
  - device_tracker.allansiphone
  - sensor.sprout
  - group.house_settings
  - alarm_control_panel.home
  - lock.front_door
  - lock.back_door
  - lock.back_gate
  - lock.garage
  - group.windows
  - group.door_sensors
  - group.leak_sensors
house_settings:
  name: House Settings
  control: hidden
  entities:
  - variable.house_state
  - alarm_control_panel.home
  - sensor.home_keypad
  - sensor.opening_summary
  - sensor.motion_summary
  - input_boolean.alarm_override
  - input_boolean.guest_mode
  - input_boolean.vacation_mode
  - input_boolean.housekeeper_mode
