- platform: template
  sensors:
    motion_summary:
      value_template: >
        {%-for state in states.binary_sensor 
          if(state.attributes.device_class=="motion" and state.state=="on")-%}
            {%-if loop.last-%}
              {%-if loop.index > 0-%}
                {%-for state in states.binary_sensor if(state.attributes.device_class=="motion" and state.state =="on")-%}
                  {{state.name}}{%-if not loop.last -%}{%-if(loop.index+1==loop.length)%} & {%else%}, {%endif-%}{%-else%} active{%endif-%}
                {%-endfor-%}
              {%-endif-%}
            {%-endif-%}
          {%-else-%}
            all clear
        {%-endfor-%}
      icon_template: >
        {%-for state in states.binary_sensor 
          if(state.attributes.device_class=="motion" and state.state=="on")-%}
            {%-if loop.last-%}
              {%-if loop.index > 0-%}
                mdi:alert
              {%-endif-%}
            {%-endif-%}
          {%-else-%}
            mdi:check
        {%-endfor-%}

- platform: template
  sensors:
    opening_summary:
      value_template: >
        {%-for state in states.binary_sensor 
          if(state.attributes.device_class=="opening" and state.state=="on")-%}
            {%-if loop.last-%}
              {%-if loop.index > 0-%}
                {%-for state in states.binary_sensor if(state.attributes.device_class=="opening" and state.state =="on")-%}
                  {{state.name}}{%-if not loop.last -%}{%-if(loop.index+1==loop.length)%} & {%else%}, {%endif-%}{%-else%} open{%endif-%}
                {%-endfor-%}
              {%-endif-%}
            {%-endif-%}
          {%-else-%}
            all clear
        {%-endfor-%}
      icon_template: >
        {%-for state in states.binary_sensor 
          if(state.attributes.device_class=="opening" and state.state=="on")-%}
            {%-if loop.last-%}
              {%-if loop.index > 0-%}
                mdi:alert
              {%-endif-%}
            {%-endif-%}
          {%-else-%}
            mdi:check
        {%-endfor-%}
