- platform: darksky
  api_key: !secret darksky_api_key
  forecast:
    - 1
  monitored_conditions:
    - icon
    - summary
    - hourly_summary
    - daily_summary
    - wind_speed
    - wind_bearing
    - precip_intensity
    - precip_probability
    - temperature
    - cloud_cover
    - temperature_max
    - temperature_min
