- platform: template
  sensors:
    next_event:
      friendly_name: Next Event
      value_template: >
        {{ strptime(states.calendar.allan.attributes.start_time, "%Y-%m-%d %H:%M:%S").strftime("%A %B %d at %H:%M") }}:
        {{ states.calendar.allan.attributes.message }}
        {%- if states.calendar.allan.attributes.location %} at {{ states.calendar.allan.attributes.location -}}
        {% endif %}
      icon_template: >-
        {% if is_state('calendar.allan', 'on') %}
          mdi:message-alert
        {% else %}
          mdi:message
        {% endif %}

- platform: template
  sensors:
    next_trip:
      friendly_name: Next Trip
      value_template: >
        {{ states.calendar.tripit.attributes.location }} on {{ strptime(states.calendar.tripit.attributes.start_time, "%Y-%m-%d %H:%M:%S").strftime("%A, %B %d") }}
      icon_template: >-
        {% if is_state('calendar.tripit', 'on') %}
          mdi:briefcase-check
        {% else %}
          mdi:home
        {% endif %}


- platform: template
  sensors:
    next_holiday:
      friendly_name: Next Holiday
      value_template: >
        {{ strptime(states.calendar.holidays_in_united_states.attributes.start_time, "%Y-%m-%d %H:%M:%S").strftime("%A, %B %d") }}:
        {{ states.calendar.holidays_in_united_states.attributes.message }}
      icon_template: >-
        {% if is_state('calendar.holidays_in_united_states', 'on') %}
          mdi:briefcase-check
        {% else %}
          mdi:domain
        {% endif %}

