- platform: plex
  host: !secret plex_host
  name: !secret plex_name
  username: !secret plex_username
  password: !secret plex_password

- platform: template
  sensors:
    plex_current_media:
      value_template: >-
        {%- if states.sensor.netcat.attributes.allanak -%}
          '{{states.sensor.netcat.attributes.allanak}}'
        {%- else -%}
          N/A
        {%- endif -%}
