#- platform: mqtt
#  state_topic: "smartthings/Garage Motion/temperature/state"
#  name: "Garage Temp"
#  unit_of_measurement: "째F"

- platform: mqtt
  state_topic: "smartthings/Master Closet Motion/temperature/state"
  name: "Master Bedroom Temp"
  unit_of_measurement: "째F"

- platform: mqtt
  state_topic: "smartthings/Master Bath Motion/temperature/state"
  name: "Master Bath Temp"
  unit_of_measurement: "째F"

- platform: mqtt
  state_topic: "smartthings/Kitchen Motion/temperature/state"
  name: "Kitchen Temp"
  unit_of_measurement: "째F"

#- platform: mqtt
#  state_topic: "smartthings/Garage Motion/motion/state"
#  name: "Garage Motion"

- platform: mqtt
  state_topic: "smartthings/Downstairs Motion/motion/state"
  name: "Downstairs Motion"

- platform: mqtt
  state_topic: "smartthings/Master Bedroom Motion/motion/state"
  name: "Master Bedroom Motion"

- platform: mqtt
  state_topic: "smartthings/Master Bath Motion/motion/state"
  name: "Master Bath Motion"

- platform: mqtt
  state_topic: "smartthings/Kitchen Motion/motion/state"
  name: "Kitchen Motion"

- platform: mqtt
  state_topic: "smartthings/Master Bath Window/contact/state"
  name: "Master Bath Window"

- platform: mqtt
  state_topic: "smartthings/Front Door ST/contact/state"
  name: "Front Door Contact"

- platform: mqtt
  state_topic: "smartthings/Garage Entry/contact/state"
  name: "Garage Entry"

- platform: mqtt
  state_topic: "smartthings/Back Door Contact/contact/state"
  name: "Back Door"

- platform: mqtt
  state_topic: "smartthings/Balcony Door/contact/state"
  name: "Balcony Door"

- platform: mqtt
  state_topic: "smartthings/Master Left Window/contact/state"
  name: "Master Bedroom Left Window"

- platform: mqtt
  state_topic: "smartthings/Master Right Window/contact/state"
  name: "Master Bedroom Right Window"

- platform: mqtt
  state_topic: "smartthings/Guest Bedroom Window/contact/state"
  name: "Guest Bedroom Window"

- platform: mqtt
  state_topic: "smartthings/Extra Bedroom Window/contact/state"
  name: "Extra Bedroom Window"

- platform: mqtt
  state_topic: "smartthings/Master Closet Motion/motion/state"
  name: "Master Closet Motion"

- platform: mqtt
  state_topic: "smartthings/Stairwell Motion/motion/state"
  name: "Stairwell Motion"
