- alias: Arm alarm at midnight when home
  trigger:
  - platform: state
    entity_id: variable.house_state
    to: 'Night'
  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.alarm_override
    state: 'off'
  action:
    - service: alarm_control_panel.alarm_arm_home
      data:
        entity_id: alarm_control_panel.home

- alias: Arm alarm when house vacated
  trigger:
  - entity_id: group.tracked_users
    platform: state
    to: away
  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.alarm_override
    state: 'off'
  action:
    - service: alarm_control_panel.alarm_arm_home
      data:
        entity_id: alarm_control_panel.home
    - service: notify.ios_allaniphone
      data:
        message: House is vacant. Arming security system
        title: Goodbye
        data:
          push:
            category: departure_event

- alias: Disarm alarm upon presence or code unlock
  trigger:
  - entity_id: group.tracked_users
    from: not_home
    platform: state
    to: home
  - entity_id: sensor.front_door_alarm_type
    platform: state
    to: '19'
  - entity_id: sensor.back_door_alarm_type
    platform: state
    to: '19'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: alarm_control_panel.home
        state: 'armed_home'
      - condition: state
        entity_id: alarm_control_panel.home
        state: 'armed_away'
  action:
    - service: alarm_control_panel.alarm_disarm
      data:
        entity_id: alarm_control_panel.home
    - service: notify.ios_allaniphone
      data:
        message: Alarm has been disarmed
        title: Welcome Home
        data:
          push:
            sound: US-EN-Morgan-Freeman-Welcome-Home.wav

- alias: Push alarm trigger notification
  trigger:
  - entity_id: alarm_control_panel.home
    platform: state
    to: triggered
  action:
    - service: notify.ios_allaniphone
      data:
        message: Security Alert
        title: Alarm Triggered!
        data_template:
          push:
            category: concerning_event
            sound: US-EN-Morgan-Freeman-Motion-Detected.wav
          entity_id: camera.downstairs
          attachment:
            url: "{{ state.sensor.camera_downstairs_url.state }}"
            content-type: jpg
