###################################
## Push a notification for login failures 
###################################

- alias: Login Failure
  hide_entity: True
  trigger:
    platform: template
    value_template: "{{ states('persistent_notification.httplogin') != 'unknown' }}"

  action:
  - alias: Push login failure notification
    data:
      message: Security Alert
      title: Login failure attempt
    service: notify.ios_allansiphone
