# Turn on upstairs music between 6-11am when motion in bathroom
- alias: Bathroom Music On in mornings
  id: bathroom_music_on
  trigger:
    - entity_id: binary_sensor.master_bath_motion_sensor
      platform: state
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '06:00:00'
        before: '11:00:00'
      
  action:
    - service: media_player.play_media
      data:
        media_content_id: http://15363.live.streamtheworld.com:80/KROQFMDIALUP_SC
        media_content_type: 'audio/mp4'
      entity_id: media_player.upstairs

# Turn off upstairs music when motion stops for 10 minutes
- alias: Bathroom Music Off
  id: bathroom_music_off
  trigger:
    - entity_id: binary_sensor.master_bath_motion_sensor
      platform: state
      to: 'off'
      for:
        minutes: 10
  condition:
  - condition: state
    entity_id: media_player.master_bathroom
    state: 'playing'
  action:
    - service: media_player.turn_off
      data:
        entity_id: media_player.upstairs

# After music shuts turned off, remind me if its garbage pickup tomorrow
- alias: Garbage day reminder
  trigger:
    - platform: state
      entity_id: media_player.upstairs
      from: 'playing'
  condition:
  - condition: time
    weekday:
      - mon
  action:
    - service: tts.google_say
      entity_id: media_player.home_group
      data:
        message: 'This is a reminder that tomorrow is garbage day'
