- alias: Front door motion or doorbell ring
  id: doorbell_ring
  trigger:
  - entity_id: binary_sensor.ring_front_door_ding
    platform: state
    to: 'on'
  - entity_id: binary_sensor.ring_front_door_motion
    platform: state
    to: 'on'
  action:
    - service: notify.ios_allaniphone
      data:
        message: "Front door motion\n{{ states.sensor.date__time.state }}"
        data:
          push:
            category: front_door_event
            sound: US-EN-Alexa-Motion-At-Front-Door.wav
          attachment:
            url: "{{ state.sensor.camera_driveway_url.state }}"
            content-type: jpeg
            hide-thumbnail: false
    - delay: '00:00:05'
#    - service: tts.amazon_polly_say
#      entity_id: media_player.home_group
#      data_template:
#        message: '<speak>Your presence has been detected and recorded, thank you</speak>'
