- alias: Front door motion or doorbell ring
  id: doorbell_ring
  trigger:
  - entity_id: binary_sensor.ring_front_door_ding
    platform: state
    to: 'on'
  - entity_id: binary_sensor.ring_front_door_motion
    platform: state
    to: 'on'
  action:
    - service: notify.ios_allaniphone
      data:
        message: Front Door Motion Detected
        data:
          push:
            category: front_door_event
            sound: US-EN-Alexa-Motion-At-Front-Door.wav
          entity_id: camera.driveway
          attachment:
            url: "{{ state.sensor.camera_driveway_url.state }}"
            content-type: jpg
