- alias: Night routine
  trigger:
    - platform: state
      entity_id: variable.house_state
      to: 'Night'
  condition:
    - condition: state
      entity_id: alarm_control_panel.home
      state: 'disarmed'
    - condition: state
      entity_id: group.tracked_users
      state: 'home'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.alarm_override
      state: 'off'
  action:
    - service: script.turn_on
      entity_id: script.goodnight
