############################################################
#
# Harmony Remote Control
#
############################################################

# Theater Hub  
############################################################
#
# Start Activity
#
############################################################

- alias: Harmony Theater
  hide_entity: True
  trigger:
  - platform: state
    entity_id: input_select.harmony_theater
    from: 'Select Input'
  action:
  - service: remote.turn_on
    entity_id: remote.theater
    data_template:
      activity: >
        {% if is_state("input_select.harmony_theater", "Shield") %}
          19494865
        {% elif is_state("input_select.harmony_theater", "Raspberry Pi") %}
          19498637
        {% elif is_state("input_select.harmony_theater", "Chromecast") %}
          23063086
        {% elif is_state("input_select.harmony_theater", "Security Cameras") %}
          19498642
        {% elif is_state("input_select.harmony_theater", "Apple TV") %}
          23252979
        {% else %}
        {% endif %}
  - service: input_select.select_option
    entity_id: input_select.harmony_theater
    data_template:
      option: "Select Input"
  
############################################################
#
# Stop Activity
#
############################################################

- alias: Harmony Theater Off
  hide_entity: True
  trigger:
  - platform: state
    entity_id: input_select.harmony_theater
    to: 'Power Off'
  action:
  - service: remote.turn_off
    entity_id: remote.theater
  - service: input_select.select_option
    entity_id: input_select.harmony_theater
    data_template:
      option: "Select Input"

# Master Bedroom Hub
############################################################
#
# Start Activity
#
############################################################

- alias: Harmony Bedroom
  hide_entity: True
  trigger:
  - platform: state
    entity_id: input_select.harmony_bedroom
    from: 'Select Input'
  action:
  - service: remote.turn_on
    entity_id: remote.bedroom
    data_template:
      activity: >
        {% if is_state("input_select.harmony_theater", "Watch TV") %}
          19494865
        {% elif is_state("input_select.harmony_theater", "Apple TV") %}
          23252979
        {% else %}
        {% endif %}
  - service: input_select.select_option
    entity_id: input_select.harmony_bedroom
    data_template:
      option: "Select Input"

############################################################
#
# Stop Activity
#
############################################################

- alias: Harmony Bedroom Off
  hide_entity: True
  trigger:
  - platform: state
    entity_id: input_select.harmony_bedroom
    to: 'Power Off'
  action:
  - service: remote.turn_off
    entity_id: remote.bedroom
  - service: input_select.select_option
    entity_id: input_select.harmony_bedroom
    data_template:
      option: "Select Input"

