############################################################
#
# HASS Theme Control
# 
############################################################
  
############################################################
#
# Set Day Mode Theme on Start
#
############################################################
    
- alias: 'Set Day theme at startup'
  initial_state: 'on'
  trigger:
  - platform: homeassistant
    event: start
  condition:
    condition: sun
    after: sunrise
    after_offset: '+00:30:00'
  action:
  - service: frontend.set_theme
    data:
      name: default
  
############################################################
#
# Set Night Mode Theme on Start
#
############################################################
    
- alias: 'Set Night theme at startup'
  initial_state: 'on'
  trigger:
  - platform: homeassistant
    event: start
  condition:
    condition: sun
    after: sunset
  action:
  - service: frontend.set_theme
    data:
      name: darkblue
  
############################################################
#
# Set Day Mode Theme
#
############################################################

- alias: Set Day Mode Theme after Sunrise
  trigger:
  - platform: sun
    event: sunrise
    offset: '+00:30:00'
  action:
  - service: frontend.set_theme
    data:
      name: default

############################################################
#
# Set Night Mode Theme
#
############################################################

- alias: Set Night Mode Theme after Sunset
  trigger:
  - platform: sun
    event: sunset
  action:
  - service: frontend.set_theme
    data:
      name: darkblue
      
