- alias: Home Assistant Update Notification
  id: hass_update_available
  trigger:
    - entity_id: updater.updater
      platform: state
  action:
    - service: notify.ios_allan_kleins_iphone
      data:
        message: Home Assistant {{ states.updater.updater.state }} is now available

- alias: SSL Certificate Expiry
  id: ssl_certificate_expiry
  trigger:
  - at: 09:00
    platform: time
  action:
    - service: notify.ios_allan_kleins_iphone
      data:
        message: SSL certificate expires in {{ states.sensor.ssl_certificate_expiry.state }} days
  condition:
    - below: '10'
      condition: numeric_state
      entity_id: sensor.ssl_certificate_expiry
