- alias: 'Housekeeper Mode Enabled'
  trigger:
    platform: state
    entity_id: input_boolean.housekeeper_mode
    to: 'on'
  action:
    service: script.turn_on
    entity_id: script.housekeeper_code_on

- alias: 'Housekeeper Mode Disabled'
  trigger:
    platform: state
    entity_id: input_boolean.housekeeper_mode
    to: 'off'
  action:
    service: script.turn_on
    entity_id: script.housekeeper_code_off

