# Washer Notification Sequence

- alias: 'Washer Start'
  trigger:
    platform: state
    entity_id: sensor.washer_running
    to: 'True'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.washer_status

- alias: 'Washer Done'
  trigger:
    platform: state
    entity_id: sensor.washer_running
    to: 'False'
    for:
      minutes: 3
  condition:
      condition: state
      entity_id: input_boolean.washer_status
      state: 'on'
  action:
    - service: notify.ios_allaniphone
      data:
        message: 'The Washer is done'
    - service: input_boolean.turn_off
      entity_id: input_boolean.washer_status
    - service: tts.google_say
      entity_id: media_player.home_group
      data:
        message: 'Washer is done'

# Dryer Notification Sequence

- alias: 'Dryer Start'
  trigger:
    platform: state
    entity_id: sensor.dryer_running
    to: 'True'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.dryer_status

- alias: 'Dryer Done'
  trigger:
    platform: state
    entity_id: sensor.dryer_running
    to: 'False'
  condition:
    condition: state
    entity_id: input_boolean.dryer_status
    state: 'on'
  action:
    - service: notify.ios_allaniphone
      data:
        message: 'The Dryer is done'
    - service: input_boolean.turn_off
      entity_id: input_boolean.dryer_status
    - service: tts.google_say
      entity_id: media_player.home_group
      data:
        message: 'Washer is done'

