- alias: Turn on kitchen lights when motion detected
  trigger:
  - entity_id: binary_sensor.kitchen_motion
    platform: state
    to: 'on'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.kitchenrgb
        brightness: 255
        color_name: >
            {%- if is_state("variable.house_state", "Evening") %}
            red
            {%- elif is_state("variable.house_state", "Night") %}
            red
            {%- else %}
            white
            {% endif %}
    - service: light.turn_on
      data_template:
          entity_id: light.kitchen_lights
          brightness: >
            {%- if is_state("variable.house_state", "Evening") %}
            15
            {%- elif is_state("variable.house_state", "Night") %}
            5
            {%- else %}
            255
            {% endif %}

- alias: Turn off kitchen lights when motion stops
  trigger:
    - entity_id: binary_sensor.kitchen_motion
      platform: state
      to: 'off'
      for:
        minutes: 5
  action:
    - service: light.turn_off
      data:
        entity_id: group.kitchen
