##############################################################################
###  New Device has connected to the network.  let everyone know.
##############################################################################

- alias: "New device connected"
  trigger:
    - platform: event
      event_type: device_tracker_new_device

  action:
    - wait_template: >-
        {{ not is_state('media_player.home_group', 'playing') }}
    - timeout: 02:00:00
    - service: tts.google_say
      entity_id: media_player.home_group
      data:
        message: "There has been a new device detected on the network.  Be sure to appropriately catagorize {{trigger.event.data.host_name}}"
##############################################################################
