- alias: Turn on perimeter lights at night
  trigger:
  - platform: state
    entity_id: variable.house_state
    to: 'Evening'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: group.outdoor_lights

- alias: Turn off perimeter lighting after sunrise
  trigger:
  - platform: state
    entity_id: variable.house_state
    to: 'Early Morning'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: group.outdoor_lights

- alias: Turn on inside lights at sunset
  trigger:
  - platform: state
    entity_id: variable.house_state
    to: 'Sunset'
  condition:
  - condition: state
    entity_id: group.tracked_users
    state: home
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: group.evening_lights
    - service: homeassistant.turn_on
      data:
        entity_id: light.staircase
        color: red
    - service: homeassistant.turn_on
      data:
        entity_id: light.hall_light
        brightness: '20'

- alias: Turn off evening lighting at midnight
  trigger:
  - platform: state
    entity_id: variable.house_state
    to: 'Night'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: group.evening_lights
