#
# Update Meta Device Tracker
#
- alias: "Update Meta Tracker Home"
  trigger:
    - platform: state
      entity_id: binary_sensor.bayesian_presence
      to: 'on'
  action:
    service: device_tracker.see
    data:
      dev_id: device_tracker.metatracker
      location_name: home

- alias: "Update Meta Tracker Away"
  trigger:
    - platform: state
      entity_id: binary_sensor.bayesian_presence
      to: 'off'
  action:
    service: device_tracker.see
    data:
      dev_id: device_tracker.metatracker
      location_name: not_home

- alias: House State to Vacation
  trigger:
    platform: time
    minutes: 5
  condition:
    - condition: state
      entity_id: group.tracked_users
      state: 'not_home'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
    - condition: template
      value_template: "{{ states.variable.house_state.state != 'Vacation' }}"
  action:
    - service: variable.set_variable
      data:
        variable: house_state
        value: "Vacation"

- alias: House State to Guest Mode
  trigger:
    platform: time
    minutes: 5
  condition:
    - condition: state
      entity_id: group.tracked_users
      state: 'not_home'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'on'
    - condition: template
      value_template: "{{ states.variable.house_state.state != 'Guest Mode' }}"
  action:
    - service: variable.set_variable
      data:
        variable: house_state
        value: "Guest Mode"
