- alias: Sunrise mode
  trigger:
  - event: sunrise
    offset: 00:15:00
    platform: sun
  action:
    - service: variable.set_variable
      data:
        variable: house_state
        value: "Early Morning"

# Wakeup and Morning routine are set in morning_routine.yaml

- alias: Afternoon mode
  id: afternoon_mode
  trigger:
  - at: '12:00'
    platform: time
  action:
    - service: variable.set_variable
      data:
        variable: house_state
        value: "Afternoon"

- alias: Sunset mode
  trigger:
  - event: sunset
    offset: 00:00:00
    platform: sun
  action:
    - service: variable.set_variable
      data:
        variable: house_state
        value: "Sunset"

- alias: Evening mode
  trigger:
  - event: sunset
    offset: 00:45:00
    platform: sun
  action:
    - service: variable.set_variable
      data:
        variable: house_state
        value: "Evening"

- alias: Night mode
  trigger:
  - at: '00:00'
    platform: time
  action:
    - service: variable.set_variable
      data:
        variable: house_state
        value: "Night"

