- alias: towel warmer on
  trigger:
  - at: '06:00'
    platform: time
  condition:
  - condition: state
    entity_id: device_tracker.allansiphone
    state: home
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.towel_rack

- alias: towel warmer off
  trigger:
  - at: '11:00'
    platform: time
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.towel_rack
