- alias: Turn on my towel warmer when I'm home in the morning
  trigger:
  - at: '06:00'
    platform: time
  condition:
  - condition: state
    entity_id: device_tracker.allaniphone
    state: home
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.towel_warmer_switch
