homeassistant:
  customize:
    alarm_control_panel.home:
      friendly_name: Security System
      homebridge_visible: true
    binary_sensor.back_door:
      icon: mdi:glassdoor
    binary_sensor.garage_entry:
      icon: mdi:glassdoor
    binary_sensor.balcony_door:
      icon: mdi:glassdoor
    binary_sensor.front_door:
      icon: mdi:glassdoor
      friendly_name: Front Door
    binary_sensor.master_bedroom_motion:
      friendly_name: Master Bedroom
    binary_sensor.stairwell_motion:
      friendly_name: Stairwell Motion
      icon: mdi:stairs
    binary_sensor.rear_bedroom_window:
      icon: mdi:window-closed
      google_assistant: false
      homebridge_visible: true
    binary_sensor.guest_bedroom_window:
      icon: mdi:window-closed
      google_assistant: false
      homebridge_visible: true
    binary_sensor.master_left_window:
      icon: mdi:window-closed
      google_assistant: false
      homebridge_visible: true
    binary_sensor.master_right_window:
      icon: mdi:window-closed
      google_assistant: false
      homebridge_visible: true
    binary_sensor.master_bath_window:
      icon: mdi:window-closed
      google_assistant: false
      homebridge_visible: true

envisalink:
  host: !secret envisalink_host
  port: 4025
  evl_version: 4
  panel_type: DSC
  user_name: !secret envisalink_password
  password: !secret envisalink_password
  code: !secret envisalink_code
  keepalive_interval: 60
  zonedump_interval: 30
  zones:
    1:
      name: 'Front Door'
      type: 'opening'
    2:
      name: 'Garage Entry'
      type: 'opening'
    3:
      name: 'Back Door'
      type: 'opening'
    4:
      name: 'Guest Bedroom Window'
      type: 'opening'
    5:
      name: 'Rear Bedroom Window'
      type: 'opening'
    6:
      name: 'Balcony Door'
      type: 'opening'
    7:
      name: 'Master Bedroom Motion'
      type: 'motion'
    8:
      name: 'Master Bath Window'
      type: 'opening'
    9:
      name: 'Stairwell Motion'
      type: 'motion'
    10:
      name: 'Master Left Window'
      type: 'opening'
    11:
      name: 'Master Right Window'
      type: 'opening'

  partitions:
    1:
      name: 'Home'

input_boolean:
  alarm_override:
    name: Alarm Override
    initial: off
    icon: mdi:cancel
  vacation_mode:
    name: Vacation Mode
    initial: off
    icon: mdi:airplane
  guest_mode:
    name: Guest Mode
    initial: off
    icon: mdi:account-multiple

automation:
  - alias: Arm alarm at midnight when home
    trigger:
      - platform: state
        entity_id: variable.house_state
        to: 'Night'
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: state
        entity_id: input_boolean.alarm_override
        state: 'off'
    action:
      - service: alarm_control_panel.alarm_arm_home
        data:
          entity_id: alarm_control_panel.home

  - alias: Arm alarm when house vacated
    trigger:
    - entity_id: group.tracked_users
      platform: state
      to: not_home
    condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.alarm_override
      state: 'off'
    action:
      - service: alarm_control_panel.alarm_arm_home
        data:
          entity_id: alarm_control_panel.home
      - service: notify.ios_allansiphone
        data:
          message: House is vacant. Arming security system
          title: Goodbye
          data:
            push:
              category: departure_event

  - alias: Disarm alarm upon presence or code unlock
    trigger:
      - entity_id: group.tracked_users
        from: not_home
        platform: state
        to: home
      - entity_id: sensor.front_door_alarm_type
        platform: state
        to: '19'
      - entity_id: sensor.back_door_alarm_type
        platform: state
        to: '19'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.home
          state: 'armed_home'
        - condition: state
          entity_id: alarm_control_panel.home
          state: 'armed_away'
    action:
      - service: alarm_control_panel.alarm_disarm
        data:
          entity_id: alarm_control_panel.home
      - service: notify.ios_allansiphone
        data:
          message: Alarm has been disarmed
          title: Welcome Home
          data:
            push:
              sound: US-EN-Morgan-Freeman-Welcome-Home.wav

  - alias: Push alarm trigger notification
    trigger:
      - entity_id: alarm_control_panel.home
        platform: state
        to: triggered
    action:
      - service: notify.ios_allansiphone
        data:
          message: Security Alert
          title: Alarm Triggered!
          data_template:
            push:
              category: concerning_event
              sound: US-EN-Morgan-Freeman-Motion-Detected.wav
            entity_id: camera.downstairs
            attachment:
              url: "{{ state.sensor.camera_downstairs_url.state }}"
              content-type: jpg
