homeassistant:
  customize:
    media_player.home_group:
      homebridge_name: Whole Home Chromecast
      homebridge_visible: true
    media_player.upstairs:
      homebridge_name: Upstairs Chromecast
      homebridge_visible: true
    media_player.guest_bedroom_speaker:
      homebridge_name: Guest Bedroom Google Home
      homebridge_visible: true
    media_player.kitchen:
      homebridge_name: Kitchen Chromecast
      homebridge_visible: true

input_number:
  google_volume:
    name: Volume
    initial: 3
    min: 0
    max: 10
    step: 0.5
    icon: mdi:volume-medium

# Dropdowns for streaming station selection
input_select:
  radio_station:
    name: Radio Station
    options:
      - KROQ
      - Jack FM
      - Nova 100
      - SmoothFM
      - SBS Chill
      - "None"
    initial: "None"
    icon: mdi:radio

# Dropdown to select media player or chromecast group
  speaker_selection:
    name: Speaker Selection
    options:
      - Everywhere
      - Upstairs
      - Downstairs
      - Living Room Home
      - Kitchen
      - Fireplace
      - Shield
      - Receiver
      - Office
      - Master Bedroom Receiver
      - Guest Bedroom Surround Sound
      - "None"
    initial: "None"
    icon: mdi:cast

# Media extractor for custom URL streaming
media_extractor:
  default_query: best

# Custom URL input
input_text:
  stream_url:
    name: Streaming URL
    initial: Enter URL

############################################################
#
# Chromecast Radio Control
#
############################################################
    
automation:
# Tell the casting device to play the requested stream_url via media_extractor component
  - alias: Stream URL Text Changed Event
    initial_state: true
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_text.stream_url
    action:
      - service: media_extractor.play_media
        data_template:
          entity_id: >
            {% if is_state("input_select.speaker_selection", "Everywhere") %} media_player.home_group
            {% elif is_state("input_select.speaker_selection", "Upstairs") %} media_player.upstairs
            {% elif is_state("input_select.speaker_selection", "Office") %} media_player.office
            {% elif is_state("input_select.speaker_selection", "Shield") %} media_player.shield
            {% elif is_state("input_select.speaker_selection", "Kitchen") %} media_player.kitchen
            {% elif is_state("input_select.speaker_selection", "Fireplace") %} media_player.master_bedroom
            {% elif is_state("input_select.speaker_selection", "Guest Bedroom") %} media_player.guest_bedroom_2
            {% elif is_state("input_select.speaker_selection", "Guest Bedroom Surround Sound") %} media_player.guest_bedroom_surround
            {% elif is_state("input_select.speaker_selection", "Shield") %} media_player.shield
            {% elif is_state("input_select.speaker_selection", "Receiver") %} media_player.receiver
            {% elif is_state("input_select.speaker_selection", "Master Bedroom Receiver") %} media_player.master_bedroom_receiver
            {% endif %}
          media_content_id: "{{states.input_text.stream_url.state}}"
          media_content_type: 'video/mp4'

############################################################
#
# Stop Streaming Radio on Chromecast
#
############################################################

  - alias: STOP Streaming Radio on CHROMECAST
    trigger:
      - platform: state
        entity_id: input_select.radio_station
        to: "None"
    action:
      - service: media_player.turn_off
        data_template:
          entity_id: >
              {% if is_state("input_select.speaker_selection", "Living Room Home") %}
                media_player.living_room_home
              {%-elif is_state("input_select.speaker_selection", "Everywhere") %}
                media_player.home_group
              {%-elif is_state("input_select.speaker_selection", "Upstairs") %}
                media_player.upstairs
              {%-elif is_state("input_select.speaker_selection", "Downstairs") %}
                media_player.downstairs
              {%-elif is_state("input_select.speaker_selection", "Office") %}
                media_player.office
              {%-elif is_state("input_select.speaker_selection", "Kitchen") %}
                media_player.kitchen
              {%-elif is_state("input_select.speaker_selection", "Fireplace") %}
                media_player.master_bedroom
              {%-elif is_state("input_select.speaker_selection", "Shield") %}
                media_player.shield
              {%-elif is_state("input_select.speaker_selection", "Guest Bedroom") %}
                media_player.guest_bedroom_2
              {%-elif is_state("input_select.speaker_selection", "Receiver") %}
                media_player.receiver
              {%-elif is_state("input_select.speaker_selection", "Master Bedroom Receiver") %}
                media_player.master_bedroom_receiver
              {%-elif is_state("input_select.speaker_selection", "Guest Bedroom Surround Sound") %}
                media_player.guest_bedroom_surround
              {% else %}
                "None"
              {% endif %}

############################################################
#
# Start Streaming Radio on Chromecast
#
############################################################
  
  - alias: START Streaming Radio on CHROMECAST
    trigger:
      - platform: state
        entity_id: input_select.radio_station
    action:
      - service: media_player.play_media
        data_template:
          entity_id: >
            {% if is_state("input_select.speaker_selection", "Living Room Home") %}
              media_player.living_room_home
            {%-elif is_state("input_select.speaker_selection", "Everywhere") %}
              media_player.home_group
            {%-elif is_state("input_select.speaker_selection", "Upstairs") %}
              media_player.upstairs
            {%-elif is_state("input_select.speaker_selection", "Downstairs") %}
              media_player.downstairs
            {%-elif is_state("input_select.speaker_selection", "Office") %}
              media_player.office
            {%-elif is_state("input_select.speaker_selection", "Kitchen") %}
              media_player.kitchen
            {%-elif is_state("input_select.speaker_selection", "Fireplace") %}
              media_player.master_bedroom
            {%-elif is_state("input_select.speaker_selection", "Shield") %}
              media_player.shield
            {%-elif is_state("input_select.speaker_selection", "Guest Bedroom") %}
              media_player.guest_bedroom_2
            {%-elif is_state("input_select.speaker_selection", "Receiver") %}
              media_player.receiver
            {%-elif is_state("input_select.speaker_selection", "Master Bedroom Receiver") %}
              media_player.master_bedroom_receiver
            {%-elif is_state("input_select.speaker_selection", "Guest Bedroom Surround Sound") %}
              media_player.guest_bedroom_surround
            {% else %}
              "None"
            {% endif %}
          media_content_id: >
            {% if is_state("input_select.radio_station", "KROQ") %}
              http://15363.live.streamtheworld.com:80/KROQFMDIALUP_SC
            {%-elif is_state("input_select.radio_station", "Jack FM") %}
              http://17793.live.streamtheworld.com:80/KCBSFMDIALUP_SC
            {%-elif is_state("input_select.radio_station", "Nova 100") %}
              http://streaming.novaentertainment.com.au/nova100
            {%-elif is_state("input_select.radio_station", "SmoothFM") %}
              http://streaming.novaentertainment.com.au/smooth915 
            {%-elif is_state("input_select.radio_station", "SBS Chill") %}
              http://shoutcast.sbs.com.au/SBSChill
            {% else %}
              "None"
            {% endif %}
          media_content_type: 'audio/mp4'
        
############################################################
#
# Adjust Volume on Chromecast
#
############################################################
  
  - alias: change volume google
    trigger:
      - platform: state
        entity_id: input_number.google_volume
    condition:
      - condition: template
        value_template: "{{ states.input_select.speaker_selection.state != 'OFF' }}"
    action:
      - service: media_player.volume_set
        data_template:
          entity_id: >
            {% if is_state("input_select.speaker_selection", "Living Room Home") %}
              media_player.living_room_home
            {%-elif is_state("input_select.speaker_selection", "Everywhere") %}
              media_player.home_group
            {%-elif is_state("input_select.speaker_selection", "Upstairs") %}
              media_player.upstairs
            {%-elif is_state("input_select.speaker_selection", "Downstairs") %}
              media_player.downstairs
            {%-elif is_state("input_select.speaker_selection", "Office") %}
              media_player.office
            {%-elif is_state("input_select.speaker_selection", "Kitchen") %}
              media_player.kitchen
            {%-elif is_state("input_select.speaker_selection", "Fireplace") %}
              media_player.master_bedroom
            {%-elif is_state("input_select.speaker_selection", "Shield") %}
              media_player.shield
            {%-elif is_state("input_select.speaker_selection", "Guest Bedroom") %}
              media_player.guest_bedroom2
            {%-elif is_state("input_select.speaker_selection", "Receiver") %}
              media_player.receiver
            {%-elif is_state("input_select.speaker_selection", "Master Bedroom Receiver") %}
              media_player.master_bedroom_receiver
            {%-elif is_state("input_select.speaker_selection", "Guest Bedroom Surround Sound") %}
              media_player.guest_bedroom_surround
            {% else %}
              "None"
            {% endif %}
          volume_level: "{{ states.input_number.google_volume.state | float / 10 }}"
  
############################################################
#
# Turn on/off Harmony activity when Chromecast devices start/stop playing
#
############################################################
  
  - alias: Turn on receiver when casting
    trigger:
      - platform: state
        entity_id: media_player.home_group
        to: 'playing'
      - platform: state
        entity_id: media_player.upstairs
        to: 'playing'
    condition:
      - condition: state
        entity_id: remote.theater
        state: 'off'
    action:
      - service: remote.turn_on
        entity_id: remote.theater
        data_template:
          activity: >
            {% if is_state("media_player.home_group", "playing") %}
              23063086
            {%-elif is_state("media_player.upstairs", "playing") %}
              23072014
            {% else %}
            {% endif %}
  
  - alias: Shut off receiver when casting stops
    trigger:
      - platform: state
        entity_id: media_player.home_group
        from: 'playing'
      - platform: state
        entity_id: media_player.upstairs
        from: 'playing'
    condition:
      - condition: template
        value_template: '{{ states.remote.theater.attributes.current_activity == "Chromecast" }}'
      - condition: template
        value_template: '{{ states.remote.theater.attributes.current_activity == "Chromecast Upstairs" }}'
    action:
      - service: remote.turn_off
        entity_id: remote.theater

############################################################
#
# Automations to hide Media Players when idle or off
# Currently one entry per group, can possible shrink this with a template later
############################################################
  
############################################################
#
# Media Player Home Group
#
############################################################
  - alias: 'Hide media_player.home_group while not playing'
    hide_entity: true
    trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: media_player.home_group
      to: 'idle'
    - platform: state
      entity_id: media_player.home_group
      to: 'off'
    action:
    - service: group.set_visibility
      entity_id: group.media_home_group
      data:
        visible: False
  
  - alias: 'Show media_player.home_group while playing'
    hide_entity: true
    trigger:
    - platform: state
      entity_id: media_player.home_group
      to: 'playing'
    - platform: state
      entity_id: media_player.home_group
      to: 'paused'
    action:
    - service: group.set_visibility
      entity_id: group.media_home_group
      data:
        visible: True
  
############################################################
#
# Media Player Upstairs Group
#
############################################################
    
  - alias: 'Hide media_player.upstairs while not playing'
    hide_entity: true
    trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: media_player.upstairs
      to: 'idle'
    - platform: state
      entity_id: media_player.upstairs
      to: 'off'
    action:
    - service: group.set_visibility
      entity_id: group.media_upstairs
      data:
        visible: False
  
  - alias: 'Show media_player.upstairs while playing'
    hide_entity: true
    trigger:
    - platform: state
      entity_id: media_player.upstairs
      to: 'playing'
    - platform: state
      entity_id: media_player.upstairs
      to: 'paused'
    action:
    - service: group.set_visibility
      entity_id: group.media_upstairs
      data:
        visible: True
  
############################################################
#
# Media Player Living Room
#
############################################################
    
  - alias: 'Hide media_player.living_room_home while not playing'
    hide_entity: true
    trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: media_player.living_room_home
      to: 'idle'
    - platform: state
      entity_id: media_player.living_room_home
      to: 'off'
    action:
    - service: group.set_visibility
      entity_id: group.media_living_room
      data:
        visible: False
  - alias: 'Show media_player.living_room while playing'
    hide_entity: true
    trigger:
    - platform: state
      entity_id: media_player.living_room_home
      to: 'playing'
    - platform: state
      entity_id: media_player.living_room_home
      to: 'paused'
    action:
    - service: group.set_visibility
      entity_id: group.media_living_room
      data:
        visible: True
############################################################
#
# Media Player Kitchen
#
############################################################
    
  - alias: 'Hide media_player.kitchen while not playing'
    hide_entity: true
    trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: media_player.kitchen
      to: 'idle'
    - platform: state
      entity_id: media_player.kitchen
      to: 'off'
    action:
    - service: group.set_visibility
      entity_id: group.media_kitchen
      data:
        visible: False
  - alias: 'Show media_player.kitchen while playing'
    hide_entity: true
    trigger:
    - platform: state
      entity_id: media_player.kitchen
      to: 'playing'
    - platform: state
      entity_id: media_player.kitchen
      to: 'paused'
    action:
    - service: group.set_visibility
      entity_id: group.media_kitchen
      data:
        visible: True
############################################################
#
# Media Player Office
#
############################################################
    
  - alias: 'Hide media_player.office while not playing'
    hide_entity: true
    trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: media_player.office
      to: 'idle'
    - platform: state
      entity_id: media_player.office
      to: 'off'
    action:
    - service: group.set_visibility
      entity_id: group.media_office
      data:
        visible: False
  - alias: 'Show media_player.office while playing'
    hide_entity: true
    trigger:
    - platform: state
      entity_id: media_player.office
      to: 'playing'
    - platform: state
      entity_id: media_player.office
      to: 'paused'
    action:
    - service: group.set_visibility
      entity_id: group.media_office
      data:
        visible: True
############################################################
#
# Media Player Spotify
#
############################################################
    
  - alias: 'Hide media_player.spotify while not playing'
    hide_entity: true
    trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: media_player.spotify
      to: 'idle'
    - platform: state
      entity_id: media_player.spotify
      to: 'off'
    action:
    - service: group.set_visibility
      entity_id: group.media_spotify
      data:
        visible: False
  - alias: 'Show media_player.spotify while playing'
    hide_entity: true
    trigger:
    - platform: state
      entity_id: media_player.spotify
      to: 'playing'
    - platform: state
      entity_id: media_player.spotify
      to: 'paused'
    action:
    - service: group.set_visibility
      entity_id: group.media_spotify
      data:
        visible: True
############################################################
#
# Media Player Guest Bedroom Home
#
############################################################
  
  - alias: 'Hide media_player.guest_bedroom while not playing'
    hide_entity: true
    trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: media_player.guest_bedroom
      to: 'idle'
    - platform: state
      entity_id: media_player.guest_bedroom
      to: 'off'
    action:
    - service: group.set_visibility
      entity_id: group.media_guest_bedroom
      data:
        visible: False
  
  - alias: 'Show media_player.guest_bedroom while playing'
    hide_entity: true
    trigger:
    - platform: state
      entity_id: media_player.guest_bedroom
      to: 'playing'
    - platform: state
      entity_id: media_player.guest_bedroom
      to: 'paused'
    action:
    - service: group.set_visibility
      entity_id: group.media_guest_bedroom
      data:
        visible: True
  
group:
  radio:
   name: Audio Streaming
   icon: mdi:cast
   entities:
    - input_select.speaker_selection
    - input_select.radio_station
    - input_text.stream_url
    - input_number.google_volume

  media_players:
   name: Media Players
   icon: mdi:cast
   view: no
   entities:
    - group.media_home_group
    - group.media_upstairs
    - group.media_living_room
    - group.media_kitchen
    - group.media_office
#    - group.media_spotify
  
  
# Split each media player into its own group so they can be hidden from view by automations when not playing
  media_home_group:
   name: Whole Home Audio
   icon: mdi:cast
   entities:
    - media_player.home_group
  
  media_upstairs:
   name: Upstairs Audio
   icon: mdi:cast
   entities:
    - media_player.upstairs
  
  media_living_room:
   name: Living Room Google Home
   icon: mdi:cast
   entities:
    - media_player.living_room_home
  
  media_kitchen:
   name: Kitchen Squeezebox
   icon: mdi:cast
   entities:
    - media_player.kitchen
  
  media_office:
   name: Office Google Home
   icon: mdi:cast
   entities:
    - media_player.office
  
  media_spotify:
   name: Spotify
   icon: mdi:cast
   entities:
    - media_player.spotify
  
