homeassistant:
  customize:
    sensor.harmony_theater_activity:
      icon: mdi:theater
    sensor.harmony_bedroom_activity:
      icon: mdi:theater

# These get autodiscovered, but just in case I need them later
#platform: harmony
#  name: Theater
#  host: harmonyhub

#platform: harmony
#  name: Master Bedroom
#  host: harmonyhub-masterbed

group:
  harmony_theater:
    name: Theater Activity
    entities:
     - sensor.plex_current_media
     - input_select.harmony_theater
     - sensor.harmony_theater_activity

  harmony_bedroom:
    name: Upstairs Media
    entities:
      - input_select.harmony_bedroom
      - sensor.harmony_bedroom_activity

sensor:
  - platform: template
    sensors:
      harmony_theater_activity:
        value_template: '{{ states.remote.harmony_theater.attributes.current_activity }}'
        friendly_name: 'Theater Input'
  - platform: template
    sensors:
      harmony_bedroom_activity:
        value_template: '{{ states.remote.master_bedroom.attributes.current_activity }}'
        friendly_name: 'Master Bedroom Input'

input_select:
  harmony_theater:
    name: Activity Selection
    options:
      - Select Input
      - Shield
      - Raspberry Pi
      - Security Cameras
      - Chromecast
      - Chromecast Upstairs
      - Apple TV
      - Power Off
    icon: mdi:remote

  harmony_bedroom:
    name: Activity Selection
    options:
      - Select Input
      - Watch TV
      - Power Off
    icon: mdi:remote

############################################################
#
# Harmony Remote Control
#
############################################################

# Theater Hub
############################################################
#
# Start Activity
#
############################################################
automation:
  - alias: Harmony Theater
    hide_entity: True
    trigger:
      - platform: state
        entity_id: input_select.harmony_theater
        from: 'Select Input'
    action:
      - service: remote.turn_on
        entity_id: remote.theater
        data_template:
          activity: >
            {% if is_state("input_select.harmony_theater", "Shield") %}
              19494865
            {% elif is_state("input_select.harmony_theater", "Raspberry Pi") %}
              19498637
            {% elif is_state("input_select.harmony_theater", "Chromecast") %}
              23063086
            {% elif is_state("input_select.harmony_theater", "Security Cameras") %}
              19498642
            {% elif is_state("input_select.harmony_theater", "Apple TV") %}
              23252979
            {% else %}
            {% endif %}
      - service: input_select.select_option
        entity_id: input_select.harmony_theater
        data_template:
          option: "Select Input"

############################################################
#
# Stop Activity
#
############################################################

  - alias: Harmony Theater Off
    hide_entity: True
    trigger:
      - platform: state
        entity_id: input_select.harmony_theater
        to: 'Power Off'
    action:
      - service: remote.turn_off
        entity_id: remote.theater
      - service: input_select.select_option
        entity_id: input_select.harmony_theater
        data_template:
          option: "Select Input"

# Master Bedroom Hub
############################################################
#
# Start Activity
#
############################################################

  - alias: Harmony Bedroom
    hide_entity: True
    trigger:
      - platform: state
        entity_id: input_select.harmony_bedroom
        from: 'Select Input'
    action:
      - service: remote.turn_on
        entity_id: remote.master_bedroom
        data_template:
          activity: >
            {% if is_state("input_select.harmony_theater", "Watch TV") %}
              27323264
            {% elif is_state("input_select.harmony_theater", "Apple TV") %}
              23252979
            {% else %}
            {% endif %}
      - service: input_select.select_option
        entity_id: input_select.harmony_bedroom
        data_template:
          option: "Select Input"

############################################################
#
# Stop Activity
#
############################################################

  - alias: Harmony Bedroom Off
    hide_entity: True
    trigger:
      - platform: state
        entity_id: input_select.harmony_bedroom
        to: 'Power Off'
    action:
      - service: remote.turn_off
        entity_id: remote.master_bedroom
      - service: input_select.select_option
        entity_id: input_select.harmony_bedroom
        data_template:
          option: "Select Input"
