# Hikvision NVR motion/line crossing detection
binary_sensor:
  - platform: hikvision
    host: !secret nvr_host
    name: NVR
    port: 80
    ssl: false
    username: !secret hikvision_user
    password: !secret hikvision_password
    customize:
      motion_3:
        ignored: True

# Hikvision Cameras
camera:
  - platform: mjpeg
    mjpeg_url: http://192.168.254.3/streaming/channels/102/httppreview
    username: !secret hikvision_user
    password: !secret hikvision_password
    name: Downstairs
  
  - platform: mjpeg
    mjpeg_url: http://192.168.254.11/streaming/channels/102/httppreview
    username: !secret hikvision_user
    password: !secret hikvision_password
    name: Backyard
  
#  - platform: mjpeg
#    mjpeg_url: http://192.168.254.5/streaming/channels/102/httppreview
#    username: !secret hikvision_user
#    password: !secret hikvision_password
#    name: Extra
  
  - platform: mjpeg
    mjpeg_url: http://192.168.254.13/streaming/channels/102/httppreview
    username: !secret hikvision_user
    password: !secret hikvision_password
    name: WestGate
  
  - platform: mjpeg
    mjpeg_url: http://192.168.254.12/streaming/channels/102/httppreview
    username: !secret hikvision_user
    password: !secret hikvision_password
    name: Driveway

# Icon customization
homeassistant:
  customize:
    binary_sensor.nvr_motion_2:
      icon: mdi:camcorder
      friendly_name: Downstairs Camera Motion
      templates:
        state: if state === 'on' return 'Active'; else return state;
    binary_sensor.nvr_line_crossing_2:
      icon: mdi:camcorder
      friendly_name: Downstairs Camera Line Crossing
      templates:
        state: if state === 'on' return 'Active'; else return state;
    binary_sensor.nvr_motion_3:
      icon: mdi:camcorder
      friendly_name: Driveway Camera Motion
      templates:
        state: if state === 'on' return 'Active'; else return state;
    binary_sensor.nvr_line_crossing_3:
      icon: mdi:camcorder
      friendly_name: Driveway Camera Line Crossing
      templates:
        state: if state === 'on' return 'Active'; else return state;
    binary_sensor.nvr_motion_4:
      icon: mdi:camcorder
      friendly_name: West Gate Camera Motion
      templates:
        state: if state === 'on' return 'Active'; else return state;
    binary_sensor.nvr_line_crossing_4:
      icon: mdi:camcorder
      friendly_name: West Gate Camera Line Crossing
      templates:
        state: if state === 'on' return 'Active'; else return state;
    binary_sensor.nvr_motion_5:
      icon: mdi:camcorder
      friendly_name: Back Yard Camera Motion
      templates:
        state: if state === 'on' return 'Active'; else return state;
    binary_sensor.nvr_line_crossing_5:
      icon: mdi:camcorder
      friendly_name: Back Yard Line Crossing
      templates:
        state: if state === 'on' return 'Active'; else return state;

automation:
  - alias: Driveway activity
    id: driveway_activity
    trigger:
      - platform: state
        entity_id: binary_sensor.nvr_line_crossing_3
        to: 'on'
    condition:
      - condition: state
        entity_id: group.tracked_users
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: state
        entity_id: input_boolean.alarm_override
        state: 'off'
    action:
      - service: notify.ios_allansiphone
        data:
          message: "Driveway Motion Detected"
          data_template:
            push:
              category: garage_event
              sound: US-EN-Alexa-Motion-At-Front-Yard.wav
            entity_id: "camera.driveway"
            attachment:
              url: "{{ states.camera.driveway.attributes.entity_picture }}"
              content-type: jpg

  - alias: Back door activity
    id: back_door_action
    trigger:
      - entity_id: binary_sensor.nvr_line_crossing_5
        platform: state
        to: 'on'
    condition:
      - condition: state
        entity_id: group.tracked_users
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: state
        entity_id: input_boolean.alarm_override
        state: 'off'
    action:
      - service: notify.ios_allansiphone
        data:
          message: "Back Yard Motion Detected"
          data_template:
            push:
              sound: US-EN-Alexa-Motion-At-Back-Door.wav
            entity_id: "camera.backyard"
            attachment:
              url: "{{ states.camera.backyard.attributes.entity_picture }}"
              content-type: jpg

  - alias: West gate activity
    id: west_gate_action
    trigger:
    - entity_id: binary_sensor.nvr_line_crossing_4
      platform: state
      to: 'on'
    condition:
      - condition: state
        entity_id: group.tracked_users
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: state
        entity_id: input_boolean.alarm_override
        state: 'off'
    action:
      - service: notify.ios_allansiphone
        data:
          message: West Gate Motion Detected
          data_template:
            push:
              sound: US-EN-Alexa-Motion-At-Back-Door.wav
            entity_id: "camera.westgate"
            attachment:
              url: "{{ states.camera.westgate.attributes.entity_picture }}"
              content-type: jpg

  - alias: Downstairs activity
    id: downstairs_action
    trigger:
    - entity_id: binary_sensor.nvr_line_crossing_2
      platform: state
      to: 'on'
    condition:
      - condition: state
        entity_id: group.tracked_users
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: state
        entity_id: input_boolean.alarm_override
        state: 'off'
    action:
      - service: notify.ios_allansiphone
        data:
          message: "Downstairs Motion"
          data_template:
            push:
            entity_id: "camera.downstairs"
            attachment:
              url: "{{ states.camera.downstairs.attributes.entity_picture }}"
              content-type: jpg
