# Xiaomi vacuum package
# Adjust icons to Roomba
homeassistant:
  customize:
    vacuum.xiaomi_vacuum_cleaner:
      icon: mdi:roomba
    switch.vacuum:
      icon: mdi:roomba

# Token obtained from mobile app sqlite database
vacuum:
  - platform: xiaomi_miio
    host: vacuum
    token: !secret xiaomi_vacuum_token

# Create virtual switch so I can turn the vacuum on from Google Home / Amazon Echo
switch:
  - platform: template
    switches:
      vacuum:
        value_template: "{{ is_state('vacuum.xiaomi_vacuum_cleaner', 'on') }}"
        turn_on:
          service: vacuum.turn_on
        turn_off:
          service: vacuum.return_to_base
